version: '2'

services:
    # Autoconfigured certbot
    consul-template-certbot:
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: host
        ports:
        - 54321:54321
        volumes:
        - ./config:/etc/dehydrated/config
        - ./templates:/app/templates
        environment:
          - 'NODE_CONFIG={"consul":{"host":"127.0.0.1"}, "templateGlobals": {"haproxy": {"httpPort": 80}}, "templates":[{"source":"templates/domains.txt.njk","path":"/etc/dehydrated/","filename":"domains.txt","command":"cat /etc/dehydrated/domains.txt && /app/dehydrated/dehydrated" }]}'
