version: '2'

services:
    # Autoconfigured certbot
    consul-template-certbot:
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: host
        ports:
        - 54321:54321
        volumes:
        - ./templates:/app/templates
        environment:
          - 'NODE_CONFIG={"consul":{"host":"127.0.0.1"}, "templates":[{"source":"templates/domains.sh.njk","path":"/bin","filename":"domains.sh","command":"cat /bin/domains.sh" }]}'
